bring_site/bring/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include
from django.views.generic import TemplateView

from . import views
from .views import StuffCategory, SearchResultsView, UserPage, LoginUser, ShowStuff, Register, EmailVerify, LoginAjaxView, RegistrationAjaxView

app_name = "bring"



urlpatterns = [
    path('', views.index, name='index'),
    path('actions/', views.action_stuffs, name='actions'),
    path('stuff/<slug:slug>', ShowStuff.as_view(), name='stuff'),
    path('category/<slug:cat_slug>', StuffCategory.as_view(), name='category'),
    path('search/', SearchResultsView.as_view(), name='search'),

    path('user/', UserPage.as_view(), name='user-page'),
    path('user/login/', LoginUser.as_view(), name='login-page'),
    path('user/logout/', views.logout_user, name='logout-user'),
    path('user/registration/', Register.as_view(), name='registration-user'),
    path('confirm_email/', views.confirm_email, name='confirm-email'),
    path('verify_email/<uidb64>/<token>', EmailVerify.as_view(), name='verify-email'),
    path('invalid_verify/', TemplateView.as_view(template_name='bring/invalid_verify.html'), name='invalid-verify'),

    path('login_ajax/', LoginAjaxView.as_view(), name='login-ajax'),
    path('registration_ajax/', RegistrationAjaxView.as_view(), name='registration-ajax'),

    path('contacts_ajax/', TemplateView.as_view(template_name='bring/modal-contacts.html'), name='contacts-ajax'),

    path('password_reset', PasswordResetView.as_view(template_name='bring/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done', PasswordResetDoneView.as_view(template_name='bring/passwort_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('favorites/', views.favorites, name='favorites'),

    path('comments/', views.comments, name='comments'),
    path('add/stuff/<slug:slug>/comment/', views.add_stuff_comment, name='add-comment'),

    path('stuff/<int:stuff_id>/fav', views.fav_stuff, name='stuff-fan'),
    path('test/', TemplateView.as_view(template_name='bring/test.html'), name='test'),
]

bring_site/bring_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    # path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
    path('', include('bring.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# url('social-auth/', include('social.apps.django_app.urls', namespace='social'))

bring_site/bring/forms.py
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms import Form
from django.core.exceptions import ValidationError

from django import forms
from django.utils.html import format_html_join, format_html

from .models import CustomUser, Comment
from .utils import send_email_for_verify
from django.utils.translation import gettext_lazy as _


def _password_validators_help_text_html():
    help_texts = [
        'Пароль має містити не меньше 8 символів',
        'Пароль не може бути лише з цифр'
    ]
    help_items = format_html_join(
        "", "<li>{}</li>", ((help_text,) for help_text in help_texts)
    )
    return format_html("<ul>{}</ul>", help_items) if help_items else ""


class RegisterUserForm(UserCreationForm):
    # username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email_reg = forms.EmailField(label='e-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    first_name = forms.CharField(label='Ім\'я', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор Паролю', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = CustomUser
        fields = ['email_reg', 'first_name',  'password1', 'password2']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            if not self.user_cache.email_verify:
                send_email_for_verify(self.request, self.user_cache)
                raise ValidationError('Email not verify. Chek email', code='invalid-login')
            else:
                self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data


class AuthenticationAjaxForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={
            "autocomplete": "email",
            "class": "form-control",
        }),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            "class": "form-control",
        }),
    )


class RegistrationAjaxForm(UserCreationForm):
    # username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email_reg = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={
            "autocomplete": "email",
            "class": "form-control",
        }),
    )
    name = forms.CharField(
        label=_("Ім'я"),
        max_length=254,
        widget=forms.TextInput(attrs={
            "autocomplete": "name",
            "class": "form-control",
        })
    )
    communication = forms.CharField(
        label=_("Спосіб зв'язку (Номер телефону, Telegram, Viber тощо)"),
        max_length=254,
        widget=forms.TextInput(attrs={
            "autocomplete": "name",
            "class": "form-control",
        }),
    )
    password1 = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),
        help_text=_password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Підтвердження паролю"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control"}),
        strip=False,
    )

    class Meta:
        model = CustomUser
        fields = ('email_reg', 'name', 'communication', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegistrationAjaxForm, self).__init__(*args, **kwargs)
        self.fields['communication'].required = False


class CommentForm(Form):
    class Meta:
        model = Comment
        fields = ['comment_text', 'rating_vote']

bring_site/bring/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import RegisterUserForm, LoginUserForm, CommentForm, RegistrationAjaxForm
from .models import *
from .utils import send_email_for_verify
from django.core.exceptions import ValidationError
from django.contrib.auth.tokens import default_token_generator as token_generator


def index(request):
    context = {
        'stuffs': Stuff.objects.filter(is_active=True).order_by('priority'),
        'banners': Banner.objects.filter(is_active=True).order_by('priority')
    }
    return render(request, template_name="bring/index.html", context=context)


def favorites(request):
    id = request.user.id
    if id:
        context = {
            'stuffs': Stuff.objects.filter(fans__id=id, is_active=True)
        }
        return render(request, template_name="bring/favorites.html", context=context)
    else:
        return redirect('bring:login-page')


def action_stuffs(request):
    context = {
        'stuffs': Stuff.objects.filter(is_active=True, is_action=True).order_by('priority'),
    }
    return render(request, template_name="bring/actions.html", context=context)


class ShowStuff(DetailView):
    model = Stuff
    template_name = 'bring/stuff.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'stuff'


def comments(request):
    context = {
        'objects': Stuff.objects.filter(is_active=True)
    }
    return render(request, template_name="bring/comments.html", context=context)


def add_stuff_comment(request, slug):
    form = CommentForm(request.POST)
    if form.is_valid() and form.data.get('comment_text') != '':
        comment_text = form.data.get('comment_text')
        rating_vote = form.data.get('rating_vote')
        if rating_vote == '':
            rating_vote = 0.0
        stuff = Stuff.objects.get(slug=slug)
        author = request.user
        new_comment = Comment(author=author, comment_text=comment_text, stuff=stuff, rating_vote=rating_vote)
        new_comment.save()
    return redirect(request.META.get('HTTP_REFERER'))


class StuffCategory(ListView):
    model = Stuff
    template_name = 'bring/category.html'
    context_object_name = 'stuffs'

    def get_queryset(self):
        return Stuff.objects.filter(cat__slug=self.kwargs['cat_slug'], is_active=True).order_by('priority')


class SearchResultsView(ListView):
    model = Stuff
    template_name = 'bring/search.html'

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('search')
        if query:
            query_search = query.lower()
            stuffs_search = Stuff.objects.filter(for_search__icontains=query_search, is_active=True)
            return render(request, template_name=self.template_name, context={
                'search_list': stuffs_search,
                'search_str': query,
            })
        return redirect('bring:index')


#################################
# def ajax_add_fav(request):
#     if request.is_ajax():
#         stuff_id = int(request.POST.get('stuff_id'))
#         fan_id = int(request.POST.get('fan_id'))
#
#         data = {
#             'added': True,
#             'stuff_id': stuff_id,
#             'fan_id': fan_id
#         }


#     def add_fav_stuff(request, stuff_id):
#         stuff = Stuff.objects.get(pk=stuff_id)
#         fan = request.user
#         try:
#             if stuff not in fan.favs.all():
#                 fan.favs.add(stuff)
#                 fan.save()
#             return redirect(request.META.get('HTTP_REFERER'))
#         except:
#             return redirect('bring:login-page')

# User


class UserPage(LoginRequiredMixin, TemplateView):
    model = CustomUser
    template_name = 'bring/user_page.html'
    extra_context = {}
    login_url = reverse_lazy('bring:login-page')


class LoginAjaxView(View):
    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return JsonResponse(data={}, status=201)
            return JsonResponse(
                data={'error': 'Логин и пароль невалидные'},
                status=400
            )
        return JsonResponse(
            data={'error': 'Введите логин и пароль'},
            status=400
        )


class RegistrationAjaxView(View):

    def post(self, request):
        email = request.POST.get('email_reg')
        name = request.POST.get('name')
        communication = request.POST.get('communication')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        username = email.split(sep='@')[0]
        if email and name and password1 and password2:
            try:
                if CustomUser.objects.get(email=email):
                    return JsonResponse(data={'error': 'Пользователь уже существует'}, status=400)
            except:
                pass
            if len(password1) < 8:
                return JsonResponse(data={'error': 'Пароль слишком короткий'}, status=400)
            if password1.isdigit():
                return JsonResponse(data={'error': 'Пароль не должен состоять только из цифр'}, status=400)
            if password1 and password1 != password2:
                return JsonResponse(data={'error': 'Пароль должен быть одиннаковым'}, status=400)
            new_user = CustomUser(username=username, email=email, name=name, communication=communication)
            new_user.set_password(password1)
            new_user.save()
            user = authenticate(email=email, password=password1)
            if user:
                send_email_for_verify(request, user)
                login(request, user)
            return JsonResponse(data={}, status=201)
        else:
            return JsonResponse(data={'error': 'Ошибка'}, status=400)


def logout_user(request):
    logout(request)
    if 'user' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('bring:index'))
    return redirect(request.META.get('HTTP_REFERER'))


class Register(View):
    template_name = 'bring/registration_page.html'

    # success_url = '/bring/user/'

    def get(self, request):
        context = {
            'form': RegisterUserForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = RegisterUserForm(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email_for_verify(request, user)
            return redirect('bring:confirm-email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class EmailVerify(View):
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('bring:index')
        return redirect('bring:invalid-verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = CustomUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                CustomUser.DoesNotExist, ValidationError):
            user = None
        return user


def confirm_email(request):
    context = {
        'text': 'Проверить почту',
    }
    return render(request, template_name="bring/confirm_email.html", context=context)


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'bring/login_page.html'

    def get_success_url(self):
        return reverse_lazy('bring:user-page')


def add_fav_stuff(request, stuff_id):
    stuff = Stuff.objects.get(pk=stuff_id)
    fan = request.user
    try:
        if stuff not in fan.favs.all():
            fan.favs.add(stuff)
            fan.save()
        return redirect(request.META.get('HTTP_REFERER'))
    except:
        return redirect('bring:login-page')


def del_fav_stuff(request, stuff_id):
    stuff = Stuff.objects.get(pk=stuff_id)
    fan = request.user
    if stuff in fan.favs.all():
        fan.favs.remove(stuff)
        fan.save()
    return redirect(request.META.get('HTTP_REFERER'))


def fav_stuff(request, stuff_id):
    stuff = Stuff.objects.get(pk=stuff_id)
    fan = request.user
    if stuff not in fan.favs.all():
        fan.favs.add(stuff)
        fan.save()
        return JsonResponse(
            data={'msg': 'Добавлено в избранное'},
            status=201
        )
    elif stuff in fan.favs.all():
        fan.favs.remove(stuff)
        fan.save()
        return JsonResponse(
            data={'msg': 'Удалено из избранного'},
            status=201
        )
    else:
        return redirect('bring:login-page')

bring_site/bring/templates/bring/actions.html
{% extends 'bring/base.html' %}
{% load static %}

{% block title %}BRING | Акція!{% endblock %}

{% block content %}
    <footer>
        <div class="h-footer">
            <h1 style="margin-top: 1.5%;">Акційні товари та пропозиції</h1>
        </div>
    

        <div class="stuffs-block">
            {% for stuff in stuffs %}
                <div class="stuff" >

                    {% if user.is_authenticated %}
                        <form action="{% url 'bring:stuff-fan' stuff.id %}" method="POST" id="favorite{{ stuff.id }}">
                        {% csrf_token %}
                        {% if stuff in user.favs.all %}
                            <div class="favorite"><img src="{% static 'bring/img/heart-yellow.png' %}" class="favorite-img"></div>
                        {% else %}
                            <div class="favorite"><img src="{% static 'bring/img/heart-border-yellow.png' %}" class="favorite-img"></div>
                        {% endif %}
                        </form>
                    {% else %}
                    <a data-bs-toggle="modal" data-bs-target="#login-ajax"><div class="favorite">
                        <img src="{% static 'bring/img/heart-border-yellow.png' %}" class="favorite-img">
                    </div></a>
                    {% endif %}

                        <div class="stuff-img-block"><a href="{{ stuff.get_absolute_url }}"><img src="{{ stuff.picture.url }}" class="stuff-img"></a></div>
                        <div class="stuff-title"><a href="{{ stuff.get_absolute_url }}">{{ stuff }}</a></div>
                        {% if stuff.comments.count > 0.0 %}
                            <div class="stuff-rating">Рейтинг: {{ stuff.rating }} <a href="{{ stuff.get_absolute_url }}">(Відгуків: {{ stuff.comments.count }})</a></div>
                        {% endif %}
                        <div class="stuff-comment-now"><a href="{{ stuff.get_absolute_url }}">Залишити відгук</a></div>
                        <div class="stuff-price">
                            {% for i in stuff.packing %}
                                {% if i.price > 0.0 %}
                                    Ціна: {{ i.price }} грн. за {{ i.short_unit_packing }}({{ i.method_of_packing }}) <br>
                                {% endif %}
                            {% empty %}
                            <a href="#">Цену уточнять по телефону</a>
                            {% endfor %}
                        </div>
                        <div class="order-now">Замовити зараз | Додати до кошику</div>
                </div>
            {% endfor %}
        </div>

        {% if stuffs.count == 0 %}
        <div class="h-footer">
            <h2>Нажаль, зараз немає акційних товарів та пропозицій :(</h2>
            <h6><a href="{% url 'bring:index' %}">Перейти на Головну сторінку</a></h6>
        </div>
        {% endif %}

    </footer>

{% endblock %}

bring_site/bring/templates/bring/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'bring/img/bring-logo.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bring/css/custom.css' %}">
</head>
<body>
    <div class="header">
        <div class="head">
            <div class="start">
                <li_head_start><div class="hamburger-menu">
                    <input id="menu__toggle" type="checkbox" />
                    <label class="menu__btn" for="menu__toggle">
                      <span></span>
                    </label>
                    <label class="menu__btn__area" id="menu__btn__area" for="menu__toggle"></label>

                    <ul class="menu__box">
                            <div class="auth-reg">
                                {% if not user.is_authenticated %}
                                <div class="auth-reg-left">
                                    <img src="{% static 'bring/img/user.png' %}" class="account">
                                </div>
                                <div class="auth-reg-right">
                                    <a class="href-modal-a" data-bs-toggle="modal" data-bs-target="#login-ajax">Вхід</a> |
                                    <a class="href-modal-a" data-bs-toggle="modal" data-bs-target="#registration-ajax" data-bs-dismiss="modal">Реєстрація</a>
                                </div>
                                {% else %}
                                <div class="auth-reg-left">
                                    <a class="href-auth-a" href="{% url 'bring:user-page' %}">
                                    <img src="{% static 'bring/img/user-online.png' %}" class="account"></a>
                                </div>
                                <div class="auth-reg-right"><a class="href-auth" href="{% url 'bring:user-page' %}">
                                    <div class="user-name">{{ user.get_name }}</div>
                                    <div class="user-email">{{ user.email }}</div></a>
                                </div>
                                {% endif %}
                            </div>


                            <li><a class="menu__item" href="{% url 'bring:actions' %}">Акції</a></li>

                            {% for category_item in categories_list_global %}
                                {% if category_item.related_stuffs|length > 0 %}
                                <li><a class="menu__item" href="{{ category_item.get_absolute_url }}">{{ category_item }}</a></li>
                                {% endif %}
                            {% endfor %}

                             <li><a class="menu__item" href="#">Доставка та оплата</a></li>
                            <li><a class="menu__item" href="{% url 'bring:comments' %}">Відгуки</a></li>
                             <li><a class="menu__item" href="#">Контакти</a></li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'bring:logout-user' %}">Вийти</a>
                            {% endif %}


                    </ul>
                    <ul class="menu__box__logo"><li><a class="menu__item__logo" href="{% url 'bring:index' %}"><img src="{% static 'bring/img/bring-logo.png' %}" class="logo"></a></li></ul>
                  </div></li_head_start>

                <li_head_start><div class="logo-block"><a href="{% url 'bring:index' %}">
                        <img src="{% static 'bring/img/bring-logo.png' %}" class="logo">
                    </a></div>
                </li_head_start>
            </div>

            <div class="center">
                <form action="{% url 'bring:search' %}" method="get" class="search">
                    <input type="text" name="search" placeholder="Пошук за товарами та полугами..." class="input" />
                    <input type="submit" name="" value="" class="submit" />     
                </form>
            </div>

            <div class="end">
                <a data-bs-toggle="modal" data-bs-target="#contacts-ajax"><img src="{% static 'bring/img/telephone.png' %}" class="favorites"></a>
                <a href="#"><img src="{% static 'bring/img/dump-truck.png' %}" class="bascket"></a>
            </div>
        </div>
    </div>

    <div class="clear"></div>

    <div class="center-mobile">
        <form action="{% url 'bring:search' %}" method="get" class="search">
            <input type="text" name="search" placeholder="Пошук за товарами та полугами..." class="input" />
            <input type="submit" name="" value="" class="submit" />
        </form>
    </div>

    <div class="clear-mobile"></div>

        {% block content %}{% endblock %}
{% include 'bring/modal_login.html' %}
{% include 'bring/modal_registration.html' %}
{% include 'bring/modal_contacts.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script src="{% static 'bring/main.js' %}"></script>


</body>
</html>

bring_site/bring/templates/bring/comments.html
{% extends 'bring/base.html' %}
{% load static %}

{% block title %}BRING | Відгуки{% endblock %}

{% block content %}
    <footer>
        <div class="h-footer">
            <h1 style="margin-top: 1.5%;">Відгуки</h1>
        </div>
        
       
        <div class="comment-form">
            
            {% for obj in objects %}
                {% if obj.comments.all %}
                <p><a href="{% url 'bring:stuff' obj.slug %}">{{ obj }}</a></p>
                {% for comment in obj.comments.all|dictsortreversed:'pub_comment_date' %}
                <p style="font-weight: bold;">{% if comment.author.first_name %}{{ comment.author.first_name }}{% else %}({{ comment.author }}){% endif %} оцінив пропозицію на {{ comment.rating_vote }}:</p>
                <p style="font-style: italic; font-weight: bold;">{{ comment }}</p>
                {% if comment.answer_by_admin %} <p>Відповідь адміністратора: {{ comment.answer_by_admin }}</p> {% endif %}
                <br>
                {% endfor %}
                {% endif %}

                
            {% endfor %}

            </div>


        

        
        
    </footer>

{% endblock %}

bring_site/bring/templates/bring/favorites.html
{% extends 'bring/base.html' %}
{% load static %}

{% block title %}BRING{% endblock %}

{% block content %}
    <footer>
        <div class="h-footer">
            <h1 style="margin-top: 1.5%;">Мені сподобались ці товари</h1>
        </div>
    

        <div class="stuffs-block">
            {% for stuff in stuffs %}
                <div class="stuff" >

                    {% if user.is_authenticated %}
                        <form action="{% url 'bring:stuff-fan' stuff.id %}" method="POST" id="favorite{{ stuff.id }}">
                        {% csrf_token %}
                        {% if stuff in user.favs.all %}
                            <div class="favorite"><img src="{% static 'bring/img/heart-yellow.png' %}" class="favorite-img"></div>
                        {% else %}
                            <div class="favorite"><img src="{% static 'bring/img/heart-border-yellow.png' %}" class="favorite-img"></div>
                        {% endif %}
                        </form>
                    {% else %}
                    <a data-bs-toggle="modal" data-bs-target="#login-ajax"><div class="favorite">
                        <img src="{% static 'bring/img/heart-border-yellow.png' %}" class="favorite-img">
                    </div></a>
                    {% endif %}

                        <div class="stuff-img-block"><a href="{{ stuff.get_absolute_url }}"><img src="{{ stuff.picture.url }}" class="stuff-img"></a></div>
                        <div class="stuff-title"><a href="{{ stuff.get_absolute_url }}">{{ stuff }}</a></div>
                        {% if stuff.comments.count > 0.0 %}
                            <div class="stuff-rating">Рейтинг: {{ stuff.rating }} <a href="{{ stuff.get_absolute_url }}">(Відгуків: {{ stuff.comments.count }})</a></div>
                        {% endif %}
                        <div class="stuff-comment-now"><a href="{{ stuff.get_absolute_url }}">Залишити відгук</a></div>
                        <div class="stuff-price">
                            {% for i in stuff.packing %}
                                {% if i.price > 0.0 %}
                                    Ціна: {{ i.price }} грн. за {{ i.short_unit_packing }}({{ i.method_of_packing }}) <br>
                                {% endif %}
                            {% empty %}
                            <a href="#">Цену уточнять по телефону</a>
                            {% endfor %}
                        </div>
                        <div class="order-now">Замовити зараз | Додати до кошику</div>
                </div>
            {% endfor %}
        </div>

        {% if stuffs.count == 0 %}
        <div class="h-footer">
            <h2>Нажаль, зараз немає акційних товарів та пропозицій :(</h2>
            <h6><a href="{% url 'bring:index' %}">Перейти на Головну сторінку</a></h6>
        </div>
        {% endif %}

    </footer>

{% endblock %}

bring_site/bring/templates/bring/invalid_verify.html
{% extends 'bring/base.html' %}

{% block content %}
<p>Ваша ссылка не корректна, залогинтесь снова</p>
{% endblock %}

bring_site/bring/templates/bring/login_page.html
{% extends 'bring/base.html' %}
{% load static %}

{% block title %}BRING | Авторизація{% endblock %}

{% block content %}
    <footer>
        <div class="h-footer">
            <h2 style="margin-top: 1.5%;">Увійти</h2>

        </div>
        



        <form method="post">
            {% csrf_token %}
            
            <div class="form-error">{{ form.non_field_errors }}</div>

            {% for f in form %}
                <p><label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
            {% endfor %}

            <button type="submit">Увійти</button>
        </form>



        <h6><a href="{% url 'bring:registration-user' %}">Реєстрація</a></h6>
        <h6><a href="{% url 'bring:password_reset' %}">Сброс пароля</a></h6>

        
        
    </footer>

{% endblock %}

bring_site/bring/templates/bring/password_reset_form.html
{% extends 'bring/base.html' %}
{% load static %}

{% block title %}BRING | Сброс пароля{% endblock %}

{% block content %}

<form action="{% url 'bring:password_reset' %}" method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit">Submit</button>
</form>

{% endblock %}

bring_site/bring/templates/bring/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      Успешный переход!!!
<script>
    window.close()
</script>
</body>
</html>